### 矩阵的基本操作

In [1]:
import numpy as np
from scipy import linalg

In [2]:
# 定义矩阵
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
# 求逆
linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
b = np.array([[5,6]]) #2D array
b

array([[5, 6]])

In [5]:
# 转置
b.T

array([[5],
       [6]])

In [6]:
# 矩阵乘法
A*b

array([[ 5, 12],
       [15, 24]])

In [7]:
A.dot(b.T) #matrix multiplication

array([[17],
       [39]])