### 求线性方程组

In [1]:
import numpy as np
from scipy import linalg

In [2]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
b = np.array([[5], [6]])
b

array([[5],
       [6]])

In [4]:
# 求解Ax=b
linalg.inv(A).dot(b)  # slow

array([[-4. ],
       [ 4.5]])

In [5]:
# 检查
A.dot(linalg.inv(A).dot(b)) - b  # check

array([[0.],
       [0.]])

In [6]:
# 直接求解
np.linalg.solve(A, b)  # fast

array([[-4. ],
       [ 4.5]])

In [7]:
# 检验
A.dot(np.linalg.solve(A, b)) - b

array([[0.],
       [0.]])