### 矩阵奇异值分解

In [1]:
import numpy as np
from scipy import linalg

In [2]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
M,N = A.shape
# 奇异值分解
U,s,Vh = linalg.svd(A)
print(U)
print(s)
print(Vh)

[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
[9.508032   0.77286964]
[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


In [4]:
# 奇异值分解 对角矩阵
Sig = linalg.diagsvd(s,M,N)
print(Sig)

[[9.508032   0.         0.        ]
 [0.         0.77286964 0.        ]]


In [5]:
print(U.dot(Sig.dot(Vh)))

[[1. 2. 3.]
 [4. 5. 6.]]
