### 多元函数无约束的最优化问题

In [1]:
# 导入基础计算库
import numpy as np
# 导入最优化库
from scipy.optimize import minimize

In [2]:
def rosen(x):
    """The Rosenbrock function"""
    return sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:-1])**2.0)

In [3]:
# 初始值
x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])
res = minimize(
    rosen, x0, method="nelder-mead",
    options={"xatol": 1e-8, "disp": True}
)
print(res)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 339
         Function evaluations: 571
       message: Optimization terminated successfully.
       success: True
        status: 0
           fun: 4.861153433422115e-17
             x: [ 1.000e+00  1.000e+00  1.000e+00  1.000e+00  1.000e+00]
           nit: 339
          nfev: 571
 final_simplex: (array([[ 1.000e+00,  1.000e+00, ...,  1.000e+00,
                         1.000e+00],
                       [ 1.000e+00,  1.000e+00, ...,  1.000e+00,
                         1.000e+00],
                       ...,
                       [ 1.000e+00,  1.000e+00, ...,  1.000e+00,
                         1.000e+00],
                       [ 1.000e+00,  1.000e+00, ...,  1.000e+00,
                         1.000e+00]]), array([ 4.861e-17,  7.652e-17,  8.114e-17,  8.633e-17,
                        8.641e-17,  2.179e-16]))


In [4]:
# 最小值点
print(res.x)

[1. 1. 1. 1. 1.]


In [5]:
# 目标函数的梯度
def rosen_der(x):
    xm = x[1:-1]
    xm_m1 = x[:-2]
    xm_p1 = x[2:]
    der = np.zeros_like(x)
    der[1:-1] = 200*(xm-xm_m1**2) - 400*(xm_p1 - xm**2)*xm - 2*(1-xm)
    der[0] = -400*x[0]*(x[1]-x[0]**2) - 2*(1-x[0])
    der[-1] = 200*(x[-1]-x[-2]**2)
    return der

In [6]:
res = minimize(
    rosen, x0, method="BFGS", jac=rosen_der,
    options={"disp": True}
)
print(res)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 25
         Function evaluations: 30
         Gradient evaluations: 30
  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 4.0130879949972905e-13
        x: [ 1.000e+00  1.000e+00  1.000e+00  1.000e+00  1.000e+00]
      nit: 25
      jac: [-5.690e-06 -2.733e-06 -2.545e-06 -7.735e-06  5.781e-06]
 hess_inv: [[ 7.588e-03  1.244e-02 ...  4.615e-02  9.222e-02]
            [ 1.244e-02  2.482e-02 ...  9.299e-02  1.857e-01]
            ...
            [ 4.615e-02  9.299e-02 ...  3.738e-01  7.462e-01]
            [ 9.222e-02  1.857e-01 ...  7.462e-01  1.494e+00]]
     nfev: 30
     njev: 30


In [7]:
# 最小值点
print(res.x)

[1.00000004 1.0000001  1.00000021 1.00000044 1.00000092]


In [8]:
# 目标函数的黑塞矩阵
def rosen_hess(x):
    x = np.asarray(x)
    H = np.diag(-400*x[:-1],1) - np.diag(400*x[:-1],-1)
    diagonal = np.zeros_like(x)
    diagonal[0] = 1200*x[0]**2-400*x[1]+2
    diagonal[-1] = 200
    diagonal[1:-1] = 202 + 1200*x[1:-1]**2 - 400*x[2:]
    H = H + np.diag(diagonal)
    return H

In [9]:
res = minimize(
    rosen, x0, method="Newton-CG",
    jac=rosen_der, hess=rosen_hess,
    options={"xtol": 1e-8, "disp": True}
)
print(res)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 24
         Function evaluations: 33
         Gradient evaluations: 33
         Hessian evaluations: 24
 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 3.5306674342205174e-17
       x: [ 1.000e+00  1.000e+00  1.000e+00  1.000e+00  1.000e+00]
     nit: 24
     jac: [ 2.687e-08  9.267e-08  3.701e-07  1.485e-06 -8.526e-07]
    nfev: 33
    njev: 33
    nhev: 24


In [10]:
# 最小值点
print(res.x)

[1.         1.         1.         0.99999999 0.99999999]


In [11]:
res = minimize(
    rosen, x0, method="trust-ncg",
    jac=rosen_der, hess=rosen_hess,
    options={"gtol": 1e-8, "disp": True}
)
print(res)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 20
         Function evaluations: 21
         Gradient evaluations: 20
         Hessian evaluations: 19
 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 1.232595164407831e-30
       x: [ 1.000e+00  1.000e+00  1.000e+00  1.000e+00  1.000e+00]
     nit: 20
     jac: [-0.000e+00  0.000e+00  0.000e+00  4.441e-14 -2.220e-14]
    nfev: 21
    njev: 20
    nhev: 19
    hess: [[ 8.020e+02 -4.000e+02 ...  0.000e+00  0.000e+00]
           [-4.000e+02  1.002e+03 ...  0.000e+00  0.000e+00]
           ...
           [ 0.000e+00  0.000e+00 ...  1.002e+03 -4.000e+02]
           [ 0.000e+00  0.000e+00 ... -4.000e+02  2.000e+02]]


In [12]:
# 最小值点
print(res.x)

[1. 1. 1. 1. 1.]


In [13]:
res = minimize(
    rosen, x0, method="trust-krylov",
    jac=rosen_der, hess=rosen_hess,
    options={"gtol": 1e-8, "disp": True}
)
print(res)

 iter inewton type    objective     ‖g₊‖_M⁻¹      leftmost         λ             γ             δ             α             β       
     0     0  cg_i -6.273083e+02  4.029038e+02  0.000000e+00  0.000000e+00  2.246107e+03  4.021147e+03  2.486853e-04  3.217671e-02

 iter inewton type    objective     ‖g₊‖_M⁻¹      leftmost         λ             γ             δ             α             β       
     0     0  cg_i -9.528585e+01  1.478412e+02  0.000000e+00  0.000000e+00  6.001708e+02  1.890129e+03  5.290645e-04  6.067939e-02

 iter inewton type    objective     ‖g₊‖_M⁻¹      leftmost         λ             γ             δ             α             β       
     0     0  cg_i -8.662599e+00  5.824611e+01  0.000000e+00  0.000000e+00  1.285783e+02  9.542387e+02  1.047956e-03  2.052100e-01

 iter inewton type    objective     ‖g₊‖_M⁻¹      leftmost         λ             γ             δ             α             β       
     0     0  cg_i -

In [14]:
# 最小值点
print(res.x)

[1. 1. 1. 1. 1.]


In [15]:
res = minimize(
    rosen, x0, method="trust-exact",
    jac=rosen_der, hess=rosen_hess,
    options={"gtol": 1e-8, "disp": True}
)
print(res)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 13
         Function evaluations: 14
         Gradient evaluations: 13
         Hessian evaluations: 14
 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 1.534303144849083e-22
       x: [ 1.000e+00  1.000e+00  1.000e+00  1.000e+00  1.000e+00]
     nit: 13
     jac: [ 7.503e-12  2.589e-11  1.048e-10  4.210e-10 -2.398e-10]
    nfev: 14
    njev: 13
    nhev: 14
    hess: [[ 8.020e+02 -4.000e+02 ...  0.000e+00  0.000e+00]
           [-4.000e+02  1.002e+03 ...  0.000e+00  0.000e+00]
           ...
           [ 0.000e+00  0.000e+00 ...  1.002e+03 -4.000e+02]
           [ 0.000e+00  0.000e+00 ... -4.000e+02  2.000e+02]]


In [16]:
# 最小值点
print(res.x)

[1. 1. 1. 1. 1.]
