### 带约束的最小二乘优化问题

这种问题在Python中计算的一般形式如下

$$
\min\limits_{\textbf{x}}\dfrac{1}{2}\sum^n_{i=1}\rho(f_i(\textbf{x})^2)\\
\text{subject to:}\\
\textbf{lb}\le \textbf{x}\le \textbf{ub}
$$

其中的$f_i(\textbf{x})$表示残差函数，一般是$y_i-\hat{y}_i$。

这里假设$f_i(\textbf{x})$的形式如下

$$
f_i(\textbf{x})=\dfrac{x_0(u^2_i+u_ix_1)}{u^2_i+u_ix_2+x_3}-y_i,\quad\quad i=1,2,\cdots,11
$$

这里的$x_1,x_2,x_3,x_0$是要求解的参数，其中的$u_i,y_i$是已知的数据。

In [1]:
import numpy as np
from scipy.optimize import least_squares

In [2]:
# 定义模型
def model(x, u):
    return x[0] * (u ** 2 + x[1] * u) / (u ** 2 + x[2] * u + x[3])
# 定义损失函数f_i(x)
def fun(x, u, y):
    return model(x, u) - y
# 损失函数的雅可比矩阵
def jac(x, u, y):
    J = np.empty((u.size, x.size))
    den = u ** 2 + x[2] * u + x[3]
    num = u ** 2 + x[1] * u
    J[:, 0] = num / den
    J[:, 1] = x[0] * u / den
    J[:, 2] = -x[0] * num * u / den ** 2
    J[:, 3] = -x[0] * num / den ** 2
    return J

In [3]:
# 数据样本
u = np.array(
    [
        4.0, 2.0, 1.0, 5.0e-1, 2.5e-1, 1.67e-1, 1.25e-1, 
        1.0e-1, 8.33e-2, 7.14e-2, 6.25e-2
    ]
)
y = np.array(
    [
        1.957e-1, 1.947e-1, 1.735e-1, 1.6e-1, 8.44e-2, 6.27e-2,
        4.56e-2, 3.42e-2, 3.23e-2, 2.35e-2, 2.46e-2
    ]
)
# 初始值
x0 = np.array([2.5, 3.9, 4.15, 3.9])
res = least_squares(
    fun, # 损失函数 f_i(x)
    x0, # 初始值
    jac=jac, # 雅可比矩阵
    bounds=(0, 100), # 变量范围
    args=(u, y), # fun中的参数
    verbose=1
)
print(res)

`ftol` termination condition is satisfied.
Function evaluations 131, initial cost 4.4383e+00, final cost 1.5375e-04, first-order optimality 4.52e-08.
     message: `ftol` termination condition is satisfied.
     success: True
      status: 2
         fun: [-1.307e-03 -1.876e-03  8.920e-03 -1.111e-02  8.352e-03
               -1.737e-04  2.584e-05  1.263e-03 -3.524e-03  6.168e-04
               -3.889e-03]
           x: [ 1.928e-01  1.913e-01  1.231e-01  1.361e-01]
        cost: 0.00015375280234150847
         jac: [[ 1.008e+00  4.638e-02 -4.676e-02 -1.169e-02]
               [ 1.000e+00  8.800e-02 -8.800e-02 -4.400e-02]
               ...
               [ 1.251e-01  9.180e-02 -1.148e-02 -1.608e-01]
               [ 1.074e-01  8.160e-02 -8.766e-03 -1.403e-01]]
        grad: [-4.526e-10 -1.445e-10  1.552e-09  8.542e-08]
  optimality: 4.516919346939224e-08
 active_mask: [0 0 0 0]
        nfev: 131
        njev: 104


In [4]:
# 最优点
print(res.x)

[0.192806   0.19130332 0.12306046 0.13607205]
